### ISSUE TITLE
Error when importing BaseCircleButton component

### ISSUE THREAD

**Issue by lautarovilas** [dd3tech/dd360-components#18]
**Description of the bug**
Cannot export the BaseCircleButton component by default or in a named way.

**Replay**
1. Go to your code
2. Try to import {BaseCircleButton} from 'dd360-ds'.
3. Try to use it
4. See the error

**Expected behavior
I expected the BaseCircleButton to be automatically imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/127885606/226392248-540734c2-ef52-47d0-b844-923641754565.png)

**Comment by lautarovilas** [comment]
Version ds installed:
![image](https://user-images.githubusercontent.com/127885606/226658265-0b2cb77f-88d8-4af6-a3aa-79d35577bd6b.png)

**Comment by tbor00** [comment]
Hey! @lautarovilas you can try with the last version
