### ISSUE TITLE
Error export by default for component TextArea

### ISSUE THREAD

**Issue by lautarovilas** [dd3tech/dd360-components#21]
**Describe the bug**
I tried to use the TextArea in the ds docs and it doesn't work, there is an error in the export default

**Screenshots**
![image](https://user-images.githubusercontent.com/127885606/226493606-4b503f49-3a49-4207-a88b-73bbb4ab64d3.png)

**Comment by tbor00** [comment]
Hey @lautarovilas, can you provide more information about this issue? 👀 

For example:

- Version installed
- How you try import this componente (with one screenshot is enough)

**Comment by tbor00** [comment]
Thank you @lautarovilas 

I check and take this issue to fix ASAP

**Comment by tbor00** [comment]
Hey! @lautarovilas you can try with the last version
