### ISSUE TITLE
Error export default Select

### ISSUE THREAD

**Issue by lautarovilas** [dd3tech/dd360-components#28]
**Describe the bug**
When upgrading to the latest version of ds, a bug was found in the docs when importing for default the Select component.

**Screenshots**
![image](https://user-images.githubusercontent.com/127885606/226765321-65c6f7c0-478d-4893-8dac-af34a7fcc0c1.png)

**Comment by tbor00** [comment]
Sorry but i check with the latest version (4.15.3) and i didn't reproduce this issue.

Can you try again with the same version or provide more information?  

<img width="448" alt="Captura de Pantalla 2023-03-21 a la(s) 23 15 55" src="https://user-images.githubusercontent.com/64227164/226784732-27835319-583c-4371-8045-b534716c8210.png">

**Comment by lautarovilas** [comment]
> Sorry but i check with the latest version (4.15.3) and i didn't reproduce this issue.
> 
> Can you try again with the same version or provide more information?
> 
> <img alt="Captura de Pantalla 2023-03-21 a la(s) 23 15 55" width="448" src="https://user-images.githubusercontent.com/64227164/226784732-27835319-583c-4371-8045-b534716c8210.png">

I have tested it with versions:
4.15.4
4.15.3
4.15.1

In all 3 versions, running npm run build gives the following error: 
![image](https://user-images.githubusercontent.com/127885606/226943882-3336f70b-2d51-4d57-84d4-0a7875e5b641.png)

**Comment by lautarovilas** [comment]
I have already detected the error, in some version change the props were modified and that was generating an error, all fixed, close the issue
