### ISSUE TITLE
Error import Row component

### ISSUE THREAD

**Issue by lautarovilas** [dd3tech/dd360-components#35]
**Describe the bug**
Error at the import Row component

**Screenshots**
![image](https://user-images.githubusercontent.com/127885606/226996515-4aa69f52-0cb7-480f-a234-cff642047554.png)

Version ds: 
![image](https://user-images.githubusercontent.com/127885606/226996560-bc44bfdf-2930-42c1-8a55-af812ed7de0e.png)

Error render: 
![image](https://user-images.githubusercontent.com/127885606/226996658-05bc39c0-3b7b-427f-b88a-ddb1c00bb952.png)

**Comment by tbor00** [comment]
You can import and use like this:

```js
import { Table } from 'dd360-ds'

<Table.Row />
```

**Comment by tbor00** [comment]
This issue was resolved in the last version. Please try again
