### ISSUE TITLE
Row component does not work correctly

### ISSUE THREAD

**Issue by lautarovilas** [dd3tech/dd360-components#42]
**Describe the bug**
The Row component does not work correctly

From what I was seeing in the code of the component, it is because the "display: grid" (in tailwind: "grid") is not applied.

You have to add only the "grid" to the css of the component.

**Screenshots**
![image](https://user-images.githubusercontent.com/127885606/227262408-903bca42-6af1-43a7-bf83-fcb918cfee32.png)

**Comment by tbor00** [comment]
Hey @lautarovilas 

Can you check if this issue was resolved? Thanks

**Comment by lautarovilas** [comment]
> Hey @lautarovilas
> 
> Can you check if this issue was resolved? Thanks

Now it works correctly, thank you!
