### ISSUE TITLE
The modal doesn't take the full size of the screen width. There is a space on the left side.

### ISSUE THREAD

**Issue by andres-bedolla** [dd3tech/dd360-components#52]
**Describe the bug**
In the modal component, when it opens, it doesn't take the full size of the screen width and there is a space on the left side regardless of whether it is mobile or full screen.

**To Reproduce**
1. Open any modal component on the UI
4. See the width size of the component on the screen and how it fits

**Expected behavior**
The modal should take the full size of the screen width, either in full screen mode and show the background shadow, or in mobile view and take the full size of the screen.

**Screenshots**
![Screen Shot 2023-03-30 at 12 38 30 p m](https://user-images.githubusercontent.com/127888795/228932824-8558b5ce-455d-4525-b58c-623ccbb67c8b.png)
![Screen Shot 2023-03-30 at 12 39 08 p m](https://user-images.githubusercontent.com/127888795/228932947-7ed64621-4708-4cbf-b9ca-b857a52308df.png)

**Desktop **
 - OS: macOS Monterey
 - Browser: Chrome
 - Version: 111.0.5563.146

**Additional context**
I don't use any other global styles other than tailwind that may interfere.

**Comment by tbor00** [comment]
I see, I think you must be referring to the overlay (the black layer behind).

- Can you provide more information about how you implements that? (code screenshot is good)
- Screen resolution?

I could not reproduce this issue

**Comment by tbor00** [comment]
This fix was included on `v5.0.3`

Thanks for the report @andres-bedolla
