### ISSUE TITLE
Multiple files support in InputFile component

### ISSUE THREAD

**Issue by andres-bedolla** [dd3tech/dd360-components#68]
**Describe the solution you'd like**
That the current InputFile component can have the feature and support for uploading multiple files.

**Describe alternatives you've considered**
The input will display a list of the uploaded files and can be handled as such.

**Additional context**
A feature something like this:
![image](https://user-images.githubusercontent.com/127888795/232151840-86232a09-1d2e-4ccb-9d7e-3310ed14582a.png)

**Comment by tbor00** [comment]
Hi @andres-bedolla, we are happy to take on this issue for you. From this point forward, our team member @jasanhdz will be following up with you to keep you updated on our progress and to address any questions or concerns you may have. 

Thank you for this feature request!

**Comment by tbor00** [comment]
This issue was completed by @jasanhdz
