### ISSUE TITLE
IconStatus background color in Select component always is error color

### ISSUE THREAD

**Issue by andres-bedolla** [dd3tech/dd360-components#76]
**Describe the bug**
The IconStatus background color in Select component is always taking the error color defined in the theme. It seems like the background error color is overwriting the other variants. I'm using v.6.0.0.

**To Reproduce**
1. At any Select component define a variant with IconStatus, such as success, warning and error.

**Expected behavior**
The IconStatus background should take the background color depending on the variant.

**Screenshots**
![image](https://user-images.githubusercontent.com/127888795/233473887-4dc3f78f-d8f4-4d15-b721-e13a3c18c031.png)

And even in the [Select documentation](https://dd360-components-docs.vercel.app/docs/form/select) is showing like that.

![image](https://user-images.githubusercontent.com/127888795/233474197-f7520182-29f9-46ab-aecf-6c1c0d7d6a37.png)

**Desktop (please complete the following information):**
 - macOS Monterey
 - Browser Chrome
 - Version 111.0.5563.146 (arm64)

**Comment by tbor00** [comment]
I see, thanks for the report! I will working on that
